### ISSUE TITLE
Get authentication/authorization working

### ISSUE THREAD

**Issue by elemental21** [elemental21/BTI#1]
Currently it's working with the default MVC database.  I need to get it converted over to our BuffaloTungsten database

**Comment by elemental21** [comment]
This was pretty simple, just changed the web.config file I was trying to run migrations again, but automatic migrations are turned on.  Now we can create/login/manage users.

**Comment by jasonwhurley** [comment]
You rock!  I'll get in there in the next day or two and give a shot on
adding DB fields.
